### ISSUE TITLE
为什么后面loss会变成负数？

### ISSUE THREAD

**Issue by orange-sun2818** [bojone/flow#2]
你好，麻烦问下，在nice.py的encoder.compile(loss=lambda y_true,y_pred: K.sum(0.5 * y_pred**2, 1),中y_pred有平方，loss应该恒为正数呀？为什么几轮迭代后loss会变成负数？这是什么原因呢？

**Comment by bojone** [comment]
负数是必然的。

最后那个loss只是完整loss的一部分，完整的loss还包括雅可比行列式的对数，这部分在每个层的定义时就加入了。

你也可以从另外一个角度理解：x是图像，被我们视为连续向量了，而连续型的交叉熵是-\int p(x)log q(x) dx，它是可以为负的。

**Comment by orange-sun2818** [comment]
理解了，谢谢！
